"""F3A: fundamentos del modelo de dominio (competidor / academia / inscripcion)

Revision ID: f3a0c1d2e3f4
Revises: 8f2b1c7d4a90
Create Date: 2026-10-04

Anade, de forma **aditiva y sin backfill**, las tablas del modelo de dominio aprobado
en `docs/21-competitor-club-registration-domain.md` (v3): academias deportivas con su
historial de nombres, competidores con su historial de nombres, afiliaciones vigentes,
inscripciones por categoria con revisiones y auditoria, log de rectificaciones y
overrides de cuota por tenant. Anade ademas dos vinculos opcionales y nullable en
`players` (`registration_id`, `competitor_id`) con ON DELETE SET NULL.

Nada existente cambia de significado: `clubs` sigue siendo el tenant, `players` la
participacion legacy por torneo, `teams` la unidad competitiva y
`stage_item_inputs.team_id` el entrant del motor (intacto). El Entrant explicito (F3E)
no se crea aqui. Ninguna tabla existente se modifica salvo las dos columnas anadidas.

Politica de borrado (doc 21 v3, §12.2): el historico de competicion nunca se elimina en
cascada desde `tournaments` (RESTRICT); identidad y afiliacion son RESTRICT; solo las
relaciones auxiliares (SET NULL) y de configuracion (CASCADE) desaparecen con su padre.

Cadena de revisiones (desviacion documentada de doc 21 v3 §12.3): `corrects_registration_id`
es RESTRICT (una revision no puede quedarse sin su origen) y `superseded_by_registration_id`
es SET NULL para que el borrado explicito y ordenado (hoja -> raiz) siga siendo posible:
con RESTRICT en ambos lados la pareja original/revision era indeleble. Por el mismo motivo
no se crea el CHECK "CORRECTED => superseded_by", que pasa a la capa de aplicacion (F3B/F3C).

Retrocompatible: la migracion puede aplicarse antes de desplegar la imagen nueva, y
`downgrade()` revierte exactamente lo anadido (BBDD vacia de estos objetos, incluidos
los tipos enum, que aqui si se pueden eliminar porque ninguna tabla los usa ya).
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str | None = "f3a0c1d2e3f4"
down_revision: str | None = "8f2b1c7d4a90"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("managed_by_club_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["managed_by_club_id"], ["clubs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_competitors_active"), "competitors", ["active"], unique=False)
    op.create_index(
        "ix_competitors_display_name_normalized",
        "competitors",
        [sa.literal_column("lower(btrim(display_name))")],
        unique=False,
    )
    op.create_index(op.f("ix_competitors_id"), "competitors", ["id"], unique=False)
    op.create_index(
        op.f("ix_competitors_managed_by_club_id"),
        "competitors",
        ["managed_by_club_id"],
        unique=False,
    )
    op.create_table(
        "domain_change_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column(
            "changed_fields", sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_label", sa.String(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_domain_change_log_entity", "domain_change_log", ["entity", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_domain_change_log_id"), "domain_change_log", ["id"], unique=False)
    op.create_table(
        "sports_clubs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("tenant_club_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_club_id"], ["clubs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sports_clubs_active"), "sports_clubs", ["active"], unique=False)
    op.create_index(op.f("ix_sports_clubs_id"), "sports_clubs", ["id"], unique=False)
    op.create_index(
        "ix_sports_clubs_name_normalized",
        "sports_clubs",
        [sa.literal_column("lower(btrim(name))")],
        unique=False,
    )
    op.create_index(
        op.f("ix_sports_clubs_tenant_club_id"), "sports_clubs", ["tenant_club_id"], unique=False
    )
    op.create_table(
        "tenant_quota_overrides",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("club_id", sa.BigInteger(), nullable=False),
        sa.Column("quota_key", sa.String(), nullable=False),
        sa.Column("quota_value", sa.Integer(), nullable=False),
        sa.Column("updated_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "quota_key", name="uq_tenant_quota_overrides_club_key"),
    )
    op.create_index(
        op.f("ix_tenant_quota_overrides_club_id"),
        "tenant_quota_overrides",
        ["club_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tenant_quota_overrides_id"), "tenant_quota_overrides", ["id"], unique=False
    )
    op.create_table(
        "competitors_name_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_by_user_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ck_competitors_name_history_range"
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competitors_name_history_competitor_id"),
        "competitors_name_history",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competitors_name_history_id"), "competitors_name_history", ["id"], unique=False
    )
    op.create_table(
        "competitors_x_sports_clubs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("sports_club_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="f", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ck_competitors_x_sports_clubs_range"
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sports_club_id"], ["sports_clubs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competitors_x_sports_clubs_competitor_id"),
        "competitors_x_sports_clubs",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competitors_x_sports_clubs_id"), "competitors_x_sports_clubs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_competitors_x_sports_clubs_sports_club_id"),
        "competitors_x_sports_clubs",
        ["sports_club_id"],
        unique=False,
    )
    op.create_index(
        "uq_competitors_x_sports_clubs_primary",
        "competitors_x_sports_clubs",
        ["competitor_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL AND is_primary"),
    )
    op.create_table(
        "sports_clubs_name_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sports_club_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_by_user_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ck_sports_clubs_name_history_range"
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sports_club_id"], ["sports_clubs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sports_clubs_name_history_id"), "sports_clubs_name_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sports_clubs_name_history_sports_club_id"),
        "sports_clubs_name_history",
        ["sports_club_id"],
        unique=False,
    )
    op.create_table(
        "tournament_registrations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tournament_id", sa.BigInteger(), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "identity_status",
            sa.Enum("UNVERIFIED", "AMBIGUOUS", "VERIFIED", name="registration_identity_status"),
            server_default="UNVERIFIED",
            nullable=False,
        ),
        sa.Column(
            "representation",
            sa.Enum("INDEPENDENT", "CLUB", name="registration_representation"),
            server_default="INDEPENDENT",
            nullable=False,
        ),
        sa.Column("sports_club_id", sa.BigInteger(), nullable=True),
        sa.Column("affiliation_id", sa.BigInteger(), nullable=True),
        sa.Column("category_key", sa.String(), nullable=True),
        sa.Column("category_label", sa.String(), nullable=True),
        sa.Column("competitor_name_snapshot", sa.String(), nullable=False),
        sa.Column("sports_club_name_snapshot", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CONFIRMED",
                "WITHDRAWN",
                "DISQUALIFIED",
                "CORRECTED",
                name="registration_status",
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("corrects_registration_id", sa.BigInteger(), nullable=True),
        sa.Column("superseded_by_registration_id", sa.BigInteger(), nullable=True),
        sa.Column("verified_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(identity_status = 'VERIFIED') = (competitor_id IS NOT NULL)",
            name="ck_tournament_registrations_identity",
        ),
        sa.CheckConstraint(
            "(representation = 'CLUB') = (sports_club_id IS NOT NULL)",
            name="ck_tournament_registrations_representation",
        ),
        sa.CheckConstraint(
            "(representation = 'CLUB') = (sports_club_name_snapshot IS NOT NULL)",
            name="ck_tournament_registrations_club_snapshot",
        ),
        # Sin CHECK "CORRECTED => superseded_by": incompatible con ON DELETE SET NULL (ver
        # comentario en bracket/schema.py). Invariante de aplicacion, no de BBDD (F3B/F3C).
        sa.CheckConstraint(
            "length(btrim(competitor_name_snapshot)) > 0",
            name="ck_tournament_registrations_snapshot_not_empty",
        ),
        sa.CheckConstraint(
            "revision = 1 OR corrects_registration_id IS NOT NULL",
            name="ck_tournament_registrations_revision",
        ),
        sa.ForeignKeyConstraint(
            ["affiliation_id"], ["competitors_x_sports_clubs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["corrects_registration_id"], ["tournament_registrations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["sports_club_id"], ["sports_clubs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["superseded_by_registration_id"], ["tournament_registrations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournaments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["verified_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tournament_registrations_category_key"),
        "tournament_registrations",
        ["category_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_registrations_competitor_id"),
        "tournament_registrations",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_registrations_corrects_registration_id"),
        "tournament_registrations",
        ["corrects_registration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_registrations_id"), "tournament_registrations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_registrations_sports_club_id"),
        "tournament_registrations",
        ["sports_club_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_registrations_status"),
        "tournament_registrations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_registrations_tournament_id"),
        "tournament_registrations",
        ["tournament_id"],
        unique=False,
    )
    op.create_index(
        "uq_tournament_registrations_current_category",
        "tournament_registrations",
        ["tournament_id", "competitor_id", "category_key"],
        unique=True,
        postgresql_where=sa.text("competitor_id IS NOT NULL AND status <> 'CORRECTED'"),
    )
    op.create_index(
        "uq_tournament_registrations_current_uncategorized",
        "tournament_registrations",
        ["tournament_id", "competitor_id"],
        unique=True,
        postgresql_where=sa.text(
            "competitor_id IS NOT NULL AND category_key IS NULL AND status <> 'CORRECTED'"
        ),
    )
    op.add_column("players", sa.Column("registration_id", sa.BigInteger(), nullable=True))
    op.add_column("players", sa.Column("competitor_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_players_competitor_id"), "players", ["competitor_id"], unique=False)
    op.create_index(
        op.f("ix_players_registration_id"), "players", ["registration_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "players",
        "tournament_registrations",
        ["registration_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "players", "competitors", ["competitor_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Las claves foraneas de `players` caen con sus columnas (drop_column): no se
    # borran aparte para no depender de nombres autogenerados.
    op.drop_index(op.f("ix_players_registration_id"), table_name="players")
    op.drop_index(op.f("ix_players_competitor_id"), table_name="players")
    op.drop_column("players", "competitor_id")
    op.drop_column("players", "registration_id")
    op.drop_index(
        "uq_tournament_registrations_current_uncategorized",
        table_name="tournament_registrations",
        postgresql_where=sa.text(
            "competitor_id IS NOT NULL AND category_key IS NULL AND status <> 'CORRECTED'"
        ),
    )
    op.drop_index(
        "uq_tournament_registrations_current_category",
        table_name="tournament_registrations",
        postgresql_where=sa.text("competitor_id IS NOT NULL AND status <> 'CORRECTED'"),
    )
    op.drop_index(
        op.f("ix_tournament_registrations_tournament_id"), table_name="tournament_registrations"
    )
    op.drop_index(op.f("ix_tournament_registrations_status"), table_name="tournament_registrations")
    op.drop_index(
        op.f("ix_tournament_registrations_sports_club_id"), table_name="tournament_registrations"
    )
    op.drop_index(op.f("ix_tournament_registrations_id"), table_name="tournament_registrations")
    op.drop_index(
        op.f("ix_tournament_registrations_corrects_registration_id"),
        table_name="tournament_registrations",
    )
    op.drop_index(
        op.f("ix_tournament_registrations_competitor_id"), table_name="tournament_registrations"
    )
    op.drop_index(
        op.f("ix_tournament_registrations_category_key"), table_name="tournament_registrations"
    )
    op.drop_table("tournament_registrations")
    op.drop_index(
        op.f("ix_sports_clubs_name_history_sports_club_id"), table_name="sports_clubs_name_history"
    )
    op.drop_index(op.f("ix_sports_clubs_name_history_id"), table_name="sports_clubs_name_history")
    op.drop_table("sports_clubs_name_history")
    op.drop_index(
        "uq_competitors_x_sports_clubs_primary",
        table_name="competitors_x_sports_clubs",
        postgresql_where=sa.text("valid_to IS NULL AND is_primary"),
    )
    op.drop_index(
        op.f("ix_competitors_x_sports_clubs_sports_club_id"),
        table_name="competitors_x_sports_clubs",
    )
    op.drop_index(op.f("ix_competitors_x_sports_clubs_id"), table_name="competitors_x_sports_clubs")
    op.drop_index(
        op.f("ix_competitors_x_sports_clubs_competitor_id"), table_name="competitors_x_sports_clubs"
    )
    op.drop_table("competitors_x_sports_clubs")
    op.drop_index(op.f("ix_competitors_name_history_id"), table_name="competitors_name_history")
    op.drop_index(
        op.f("ix_competitors_name_history_competitor_id"), table_name="competitors_name_history"
    )
    op.drop_table("competitors_name_history")
    op.drop_index(op.f("ix_tenant_quota_overrides_id"), table_name="tenant_quota_overrides")
    op.drop_index(op.f("ix_tenant_quota_overrides_club_id"), table_name="tenant_quota_overrides")
    op.drop_table("tenant_quota_overrides")
    op.drop_index(op.f("ix_sports_clubs_tenant_club_id"), table_name="sports_clubs")
    op.drop_index("ix_sports_clubs_name_normalized", table_name="sports_clubs")
    op.drop_index(op.f("ix_sports_clubs_id"), table_name="sports_clubs")
    op.drop_index(op.f("ix_sports_clubs_active"), table_name="sports_clubs")
    op.drop_table("sports_clubs")
    op.drop_index(op.f("ix_domain_change_log_id"), table_name="domain_change_log")
    op.drop_index("ix_domain_change_log_entity", table_name="domain_change_log")
    op.drop_table("domain_change_log")
    op.drop_index(op.f("ix_competitors_managed_by_club_id"), table_name="competitors")
    op.drop_index(op.f("ix_competitors_id"), table_name="competitors")
    op.drop_index("ix_competitors_display_name_normalized", table_name="competitors")
    op.drop_index(op.f("ix_competitors_active"), table_name="competitors")
    op.drop_table("competitors")
    # Los tipos enum creados por esta migracion se eliminan al final: sin las tablas que
    # los usan, el downgrade deja la base exactamente como estaba.
    op.execute("DROP TYPE IF EXISTS registration_status")
    op.execute("DROP TYPE IF EXISTS registration_representation")
    op.execute("DROP TYPE IF EXISTS registration_identity_status")
    # ### end Alembic commands ###
